// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PanopticonServiceClient is the client API for PanopticonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanopticonServiceClient interface {
	Report(ctx context.Context, in *HostProcessReportRequest, opts ...grpc.CallOption) (*HostActionResponse, error)
}

type panopticonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPanopticonServiceClient(cc grpc.ClientConnInterface) PanopticonServiceClient {
	return &panopticonServiceClient{cc}
}

func (c *panopticonServiceClient) Report(ctx context.Context, in *HostProcessReportRequest, opts ...grpc.CallOption) (*HostActionResponse, error) {
	out := new(HostActionResponse)
	err := c.cc.Invoke(ctx, "/v1.PanopticonService/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanopticonServiceServer is the server API for PanopticonService service.
// All implementations must embed UnimplementedPanopticonServiceServer
// for forward compatibility
type PanopticonServiceServer interface {
	Report(context.Context, *HostProcessReportRequest) (*HostActionResponse, error)
	mustEmbedUnimplementedPanopticonServiceServer()
}

// UnimplementedPanopticonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPanopticonServiceServer struct {
}

func (UnimplementedPanopticonServiceServer) Report(context.Context, *HostProcessReportRequest) (*HostActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedPanopticonServiceServer) mustEmbedUnimplementedPanopticonServiceServer() {}

// UnsafePanopticonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanopticonServiceServer will
// result in compilation errors.
type UnsafePanopticonServiceServer interface {
	mustEmbedUnimplementedPanopticonServiceServer()
}

func RegisterPanopticonServiceServer(s grpc.ServiceRegistrar, srv PanopticonServiceServer) {
	s.RegisterService(&PanopticonService_ServiceDesc, srv)
}

func _PanopticonService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostProcessReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanopticonServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PanopticonService/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanopticonServiceServer).Report(ctx, req.(*HostProcessReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PanopticonService_ServiceDesc is the grpc.ServiceDesc for PanopticonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PanopticonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PanopticonService",
	HandlerType: (*PanopticonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _PanopticonService_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/server.proto",
}
